# Generated by Django 2.2.5 on 2019-10-02 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PictureShaderSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('touch_radius', models.FloatField(default=0.15)),
                ('particle_random', models.FloatField(default=2.0)),
                ('particle_depth', models.FloatField(default=4.0)),
                ('particle_size', models.FloatField(default=1.5)),
            ],
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Maximum recommended size: 800x600', upload_to='')),
                ('description', models.CharField(blank=True, max_length=256, null=True)),
                ('shader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='demo.PictureShaderSettings')),
            ],
        ),
    ]
