# Generated by Django 2.2.5 on 2019-09-23 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artworkinformation',
            name='url',
            field=models.URLField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='uid',
            field=models.CharField(max_length=36),
        ),
    ]
