# Generated by Django 2.2.5 on 2019-09-23 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0002_auto_20190923_1631'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artworkinformation',
            old_name='abstract',
            new_name='summary',
        ),
    ]
