# Generated by Django 2.2.5 on 2019-09-23 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0003_auto_20190923_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='artworkinformation',
            name='interactive',
            field=models.BooleanField(default=True),
        ),
    ]
