# Generated by Django 2.2.5 on 2019-10-02 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0004_artworkinformation_interactive'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtworkStatistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interactions', models.IntegerField(default=0)),
                ('visits', models.IntegerField(default=0)),
                ('likes', models.IntegerField(default=0)),
                ('avg_time', models.FloatField(default=0)),
                ('max_time', models.FloatField(default=0)),
                ('min_time', models.FloatField(default=0)),
                ('hashtags', models.CharField(blank=True, default='', max_length=512, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='artworkinformation',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='artwork',
            name='stats',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='artworks.ArtworkStatistics'),
        ),
    ]
