# Generated by Django 2.2.5 on 2019-11-03 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0005_auto_20191002_1841'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtworkQueryImageResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('favicon', models.ImageField(blank=True, upload_to='')),
                ('image', models.ImageField(upload_to='')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ArtworkQueryTextResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('favicon', models.ImageField(blank=True, upload_to='')),
                ('title', models.CharField(blank=True, default='', max_length=512, null=True)),
                ('abstract', models.CharField(blank=True, default='', max_length=1024, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='applicationsettings',
            options={'verbose_name': 'AR application settings', 'verbose_name_plural': 'AR shader settings'},
        ),
        migrations.AlterModelOptions(
            name='artwork',
            options={'verbose_name': 'AR artwork', 'verbose_name_plural': 'AR artworks'},
        ),
        migrations.AlterModelOptions(
            name='artworkinformation',
            options={'verbose_name': 'AR artwork information', 'verbose_name_plural': 'AR artwork informations'},
        ),
        migrations.AlterModelOptions(
            name='shaderparameters',
            options={'verbose_name': 'AR shader parameters', 'verbose_name_plural': 'AR shader parameters'},
        ),
        migrations.AddField(
            model_name='artwork',
            name='query_keyword',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
