# Generated by Django 2.2.5 on 2019-11-03 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0006_auto_20191103_1654'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtworkQueryResultWebsite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('favicon', models.ImageField(blank=True, upload_to='')),
            ],
        ),
        migrations.RemoveField(
            model_name='artworkqueryimageresult',
            name='favicon',
        ),
        migrations.RemoveField(
            model_name='artworkquerytextresult',
            name='favicon',
        ),
        migrations.AddField(
            model_name='artworkqueryimageresult',
            name='weight',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='artworkquerytextresult',
            name='weight',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='artworkqueryimageresult',
            name='website',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='artworks.ArtworkQueryResultWebsite'),
        ),
        migrations.AddField(
            model_name='artworkquerytextresult',
            name='website',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='artworks.ArtworkQueryResultWebsite'),
        ),
    ]
