# Generated by Django 2.2.5 on 2019-11-03 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0007_auto_20191103_1721'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artworkqueryresultwebsite',
            name='url',
        ),
        migrations.AddField(
            model_name='artworkqueryresultwebsite',
            name='domain',
            field=models.CharField(default='example.org', max_length=64),
        ),
    ]
