# Generated by Django 2.2.5 on 2019-11-03 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0008_auto_20191103_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artworkqueryresultwebsite',
            name='favicon',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
