# Generated by Django 2.2.5 on 2019-11-03 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0009_auto_20191103_1743'),
    ]

    operations = [
        migrations.AddField(
            model_name='artworkqueryimageresult',
            name='artwork',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='artworks.Artwork'),
        ),
        migrations.AddField(
            model_name='artworkquerytextresult',
            name='artwork',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='artworks.Artwork'),
        ),
    ]
