# Generated by Django 2.2.5 on 2019-11-03 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0010_auto_20191103_1812'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artwork',
            name='stats',
        ),
        migrations.AddField(
            model_name='artwork',
            name='avg_time',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='artwork',
            name='interactions',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='artwork',
            name='likes',
            field=models.IntegerField(default=0.0),
        ),
        migrations.AddField(
            model_name='artwork',
            name='max_time',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='artwork',
            name='min_time',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='artwork',
            name='score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='artwork',
            name='visits',
            field=models.IntegerField(default=0.0),
        ),
        migrations.DeleteModel(
            name='ArtworkInformation',
        ),
        migrations.DeleteModel(
            name='ArtworkStatistics',
        ),
    ]
