# Generated by Django 2.2.5 on 2019-11-03 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0011_auto_20191103_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artworkqueryimageresult',
            name='url',
            field=models.URLField(max_length=512),
        ),
        migrations.AlterField(
            model_name='artworkquerytextresult',
            name='abstract',
            field=models.CharField(blank=True, default='', max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='artworkquerytextresult',
            name='url',
            field=models.URLField(max_length=512),
        ),
    ]
