# Generated by Django 2.2.5 on 2019-11-05 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0012_auto_20191103_2024'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtworkGraphSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x_dim', models.IntegerField(default=5)),
                ('y_dim', models.IntegerField(default=5)),
                ('z_dim', models.IntegerField(default=3)),
                ('max_lines', models.IntegerField(default=2)),
                ('density', models.IntegerField(default=7)),
                ('seed', models.IntegerField(default=9)),
                ('random_seed', models.BooleanField(default=False)),
                ('min_distance', models.FloatField(default=3.0)),
                ('duration', models.FloatField(default=1.0)),
                ('y_mov', models.FloatField(default=0.05)),
                ('x_mov', models.FloatField(default=0.05)),
                ('z_mov', models.FloatField(default=0.05)),
            ],
        ),
        migrations.RenameField(
            model_name='artworkquerytextresult',
            old_name='abstract',
            new_name='body',
        ),
        migrations.CreateModel(
            name='ArtworkGraphNode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('kind', models.IntegerField(choices=[(0, 'ARTWORK CARD'), (1, 'WEB QUERY'), (2, 'IMAGES GALLERY')], default=5)),
                ('position', models.IntegerField(default=0, help_text='Interactive node position in graph (zero based)')),
                ('artwork', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='artworks.Artwork')),
            ],
        ),
        migrations.CreateModel(
            name='ArtworkCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('author', models.CharField(max_length=64)),
                ('abstract', models.CharField(blank=True, default='', max_length=2048, null=True)),
                ('body', models.CharField(blank=True, default='', max_length=4096, null=True)),
                ('artwork', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='artworks.Artwork')),
            ],
        ),
    ]
