# Generated by Django 2.2.5 on 2019-11-05 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0014_artworkgraphsettings_artwork'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artworkcard',
            name='abstract',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='artworkcard',
            name='body',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='artworkqueryimageresult',
            name='url',
            field=models.URLField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='artworkqueryresultwebsite',
            name='domain',
            field=models.CharField(default='example.org', max_length=128),
        ),
        migrations.AlterField(
            model_name='artworkquerytextresult',
            name='body',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='artworkquerytextresult',
            name='title',
            field=models.CharField(blank=True, default='', max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='artworkquerytextresult',
            name='url',
            field=models.URLField(max_length=1024),
        ),
    ]
