# Generated by Django 2.2.5 on 2019-11-05 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0015_auto_20191105_2212'),
    ]

    operations = [
        migrations.AddField(
            model_name='artworkcard',
            name='date',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='artworkcard',
            name='author',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='artworkcard',
            name='title',
            field=models.CharField(max_length=128),
        ),
    ]
