# Generated by Django 2.2.5 on 2019-11-05 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0016_auto_20191105_2222'),
    ]

    operations = [
        migrations.AddField(
            model_name='artworkcard',
            name='author_info',
            field=models.CharField(default='', max_length=128),
        ),
    ]
