# Generated by Django 2.2.5 on 2020-01-20 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0017_artworkcard_author_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='UmanoProcess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=36)),
                ('name', models.CharField(max_length=64)),
            ],
        ),
    ]
