# Generated by Django 2.2.5 on 2020-01-20 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0018_umanoprocess'),
    ]

    operations = [
        migrations.AddField(
            model_name='umanoprocess',
            name='host',
            field=models.CharField(default='HAL', max_length=64),
        ),
    ]
