HAL_BROKER_URL = 'amqp://guest:guest@localhost'
HAL_EXCHANGE_NAME = "umano"

HAL_DATA_ADAMSHAND_COLLECTION = "adam.data"
HAL_DATA_AR_COLLECTION = "ar.data"
HAL_DATA_MACHINES_COLLECTION = "machine.data"
HAL_DATA_ONEHAND_COLLECTION = "onehand.data"
HAL_DATA_SERVICES_COLLECTION = "service.data"
HAL_DATA_SOFTWARE_COLLECTION = "software.data"

ONEHAND_MAX_HOST = "127.0.0.1"
ONEHAND_MAX_PORT = 8888

ONEHAND_OSC_DURER_FREQ_ADDRESS = "/umano/onehand/durer/freq"
ONEHAND_OSC_DURER_AMP_ADDRESS = "/umano/onehand/durer/amp"
ONEHAND_OSC_HAND_FREQ_ADDRESS = "/umano/onehand/hand/freq"
ONEHAND_OSC_HAND_AMP_ADDRESS = "/umano/onehand/hand/amp"

ONEHAND_OSC_BIGBANG_ADDRESS = "/umano/onehand/bang/bigbang"

ONEHAND_HANDPOSE_MODEL_URL = "http://posefs1.perception.cs.cmu.edu/OpenPose/models/hand/pose_iter_102000.caffemodel"

ADAM_SERIAL_BAUDRATE = 115200
ADAM_SERIAL_PRESSURE_PORT = "COM4"
ADAM_SERIAL_EGM_PORT = "COM5"
ADAM_SERIAL_EGM_MAX_VALUE = 1023
ADAM_SERIAL_ENCODING = "UTF-8"

ADAM_OSC_RECEIVER_HOST = "127.0.0.1"
ADAM_OSC_RECEIVER_PORT = 8889
ADAM_OSC_PRESSURE_ADDRESS = "/umano/adam/pressure"

